# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/svelte"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sveltekit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sveltekit-advanced"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vanilla"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
